Feature/#56 encoding adapter
cryptomator/fuse-nio-adapter pull request #57
Opened 2021-03-05 12:18 UTC by infeo

Closes #56.

## Implemented Solution
Replacing the usage of the iconv-module by encoding/decoding strings in the FuseNioAdapter itself.

## Implementation Details
A new package is added with the Interface `BufferEncoder`. It requires the method `ByteBuffer encode(CharSequence s)` to be implemented. Two example and one default implementations are given.

This interface is integrated into the project by adding it as a instance variable of the `ReadOnlyAdapter`, which can be set by calling the correct factory method of the `AdapterFactory`. Any write of a String into a native FUSE buffer is replaced by writing a byte buffer with the desired encoding. The FUSE read and write methods are not touched.

Additionally, each string constructed from a FUSE callback is normalized with NFC. This behaviour is also documented.

## Remarks
If the "normal" UTF-8-NFD encoding is sufficient needs to be tested, there is the possibility that our own NFD encoding scheme needs to be implemented. (see https://apple.stackexchange.com/questions/10476/how-to-enter-special-characters-so-that-bash-terminal-understands-them) A suitable testcharacter would be 切 (U+FA00).

2021-03-05 14:53 UTC, overheadhunter requested changes
So far this PR only considers unidirectional encoding: When data flows in the NIO→FUSE direction, the desired encoding is applied (i.e. during dir listings).

However, for other calls, a hard-coded normalization to NFC is applied (which should be configurable), but no re-encoding happens. In other words: If I call any fuse method with a ISO 8859-1 encoded file path, a byte sequence will get created from it, incorrectly using UTF-8.

What we need, to get rid of iconv, isn't _encoding_ but _transcoding_ with **two** configurable sides.

I imagine a builder pattern using some fluent API like this:

```java
var fileNameTranscoder = FileNameTranscoder.usingInternalEncoding(UTF_8).usingDesiredEncoding(UTF_8).usingDesiredNormalization(NFD);
```

normalization can default to NFC. If both sides use the same Normalization, we can internally skip it. If both sides use the same encoding, we can skip transcoding, too. So the transcoder will essentially become an "identity" transformation.

Passing this two-sided file name transcoder to the FuseNioAdapterComponent.Builder is the right approach.

2021-03-05 14:53 UTC, overheadhunter commented on src/main/java/org/cryptomator/frontend/fuse/AdapterFactory.java
> +		return comp.readWriteAdapter();
```suggestion
		return createReadWriteAdapter(root, maxFileNameLength, new DefaultEncoder());
```

2021-03-05 14:53 UTC, overheadhunter commented on src/main/java/org/cryptomator/frontend/fuse/FuseNioAdapterModule.java
> +
If there is only one encoder, you neither need `@Named()` nor this provider

2021-03-05 14:53 UTC, overheadhunter commented on src/main/java/org/cryptomator/frontend/fuse/ReadOnlyAdapter.java
> +		var normalizedAbsolutePath = Normalizer.normalize(absolutePath, Normalizer.Form.NFC);
In order to replace iconv, we don't want hard-coded UTF8-NFC. Instead both ends should be configurable, as discussed in #56

2021-03-05 14:53 UTC, overheadhunter commented on src/main/java/org/cryptomator/frontend/fuse/encoding/UTF8NFCEncoder.java
> +	private final static Charset UTF8 = StandardCharsets.UTF_8;
Use static import rather than re-declaring constants.

2021-03-05 14:53 UTC, overheadhunter commented on src/main/java/org/cryptomator/frontend/fuse/encoding/UTF8NFDEncoder.java
> +	private final static Charset UTF8 = StandardCharsets.UTF_8;
Use static import rather than re-declaring constants.

2021-03-05 14:53 UTC, overheadhunter commented on src/main/java/org/cryptomator/frontend/fuse/FuseNioAdapterComponent.java
> +		Builder toFuseEncoder(@Named("toFuseEncoder") BufferEncoder toFuseEncoder);
I don't understand the name `toFuseEncoder`. See my comment in #56 regarding naming the two different sides in a transcoding process.

2021-03-05 14:53 UTC, overheadhunter commented on src/main/java/org/cryptomator/frontend/fuse/ReadOnlyAdapter.java
> + * Any (string) path from a fuse callback is normalized into its NFC representation before it is transformed into a {@link java.nio.file.Path}.
Actually in order to replace iconv, we don't want hard-coded NFC. Both sides need to be configurable.

2021-03-05 14:53 UTC, overheadhunter commented on src/main/java/org/cryptomator/frontend/fuse/ReadOnlyAdapter.java
> +		var normalizedAbsolutePath = Normalizer.normalize(absolutePath, Normalizer.Form.NFC);
furthermore, resolvePath is no only called when filenames are passed from nio→fuse, but also fuse→nio. In the latter case, we need reverse transcoding.

2021-03-08 11:35 UTC, infeo commented
This PR is closed in favor of #57

2021-03-08 11:35 UTC, closed without merging