Remove guava
cryptomator/fuse-nio-adapter pull request #77
Opened 2023-06-10 22:55 UTC by Sineaggi

Follow-up to https://github.com/cryptomator/fuse-nio-adapter/pull/70 and https://github.com/cryptomator/fuse-nio-adapter/pull/71, removes guava as a dependency. In a few cases where there isn't an exact replacement in the jdk, I've substituted the existing code with something else.

Biggest things to scrutinize:
* The strip leading `/` characters from method using a StringBuilder
* The DirectoryStream to Stream migration
* The Splitter/Joiner replacement

2023-06-10 22:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cryptomator/fuse-nio-adapter?pullRequest=77) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cryptomator/fuse-nio-adapter?pullRequest=77) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cryptomator/fuse-nio-adapter?pullRequest=77) it.</sub>

2023-06-11 07:58 UTC, overheadhunter approved these changes
Perfect, thank you for this contribution!

2023-06-11 20:27 UTC, overheadhunter requested changes
Oh, Guava can be removed from `suppression.xml` as well 😀

2023-06-11 23:20 UTC, Sineaggi commented
> Oh, Guava can be removed from `suppression.xml` as well 😀

Ah good catch, cleaned up that and a leftover dependency property.

2023-06-12 07:09 UTC, overheadhunter approved these changes

2023-06-12 07:21 UTC, merged

2023-06-12 07:21 UTC, overheadhunter commented
Thank you so much!